server:
  port: 8080

spring:
  application:
    name: SearchLight-Health
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
        ddl-auto: update
  datasource:
    platform: h2
    url: jdbc:h2:mem:slDb;DB_CLOSE_DELAY=-1
    username: searchlight
    password: searchlight!234
    driverClassName: org.h2.Driver
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE